services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:${SERVER_PORT}"
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - WEATHER_API_URL=${WEATHER_API_URL}
      - SERVER_PORT=${SERVER_PORT}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_TTL=${REDIS_TTL}
    depends_on:
      - postgres
      - redis
      - kafka
    networks:
      - weather-network

networks:
  weather-network:
    external: true

    